experiment_name: laesr_default
seed: 42
device: cuda

scale: 4
patch_size: 192
batch_size: 6
num_workers: 4
accumulation_steps: 1
max_steps: 2000
val_interval: 500
save_interval: 1200

optimizer:
  lr: 2.0e-4
  betas: [0.9, 0.99]
  weight_decay: 0.0

scheduler:
  type: cosine
  warmup_steps: 1000

loss:
  charbonnier_weight: 1.0
  edge_weight: 0.3
  perceptual_weight: 0.0
  antibanding_weight: 0.02
  antibanding_grad_thr: 0.02
  chroma_tv_weight: 0.01
  chroma_keep_weight: 0.1
  antihalo_weight: 0.0
  antihalo_edge_thr: 0.05
  antihalo_blur: 5
  use_gan: false
  gan_weight: 0.0
  r1_gamma: 0.0
  gan_warmup_steps: 0

data:
  hr_dir: data/commons/images
  commons_dir: data/commons
  crop_size: 192
  use_tile_dataset: true
  tile_stride: 192
  scale_choices: [4]
  jpeg_q_range: [80, 95]
  noise_sigma_range: [0.0, 2.0]
  blur_kernel_size: 5
  blur_sigma_range: [0.2, 1.2]

train:
  mixed_precision: true
  ema: true
  ema_decay: 0.999
  grad_clip: 1.0
  compile: true

infer:
  tile_size: 256
  tile_overlap: 16
  temporal_smoothing: false
  smoothing_alpha: 0.7
  half_precision: true
  autotile: true
  min_tile: 128
  post_sharpen:
    enabled: true
    amount: 0.35
    radius: 3
    threshold: 0.01
  tta: false

paths:
  runs_dir: runs
  checkpoints_dir: runs/checkpoints
  logs_dir: runs/logs
  samples_dir: runs/samples

