experiment_name: laesr_default
seed: 42
device: cuda

scale: 4
patch_size: 256
batch_size: 12
model:
  base_channels: 80
  num_blocks: 18
num_workers: 8
accumulation_steps: 3
max_steps: 30000
val_interval: 1000
save_interval: 2000

optimizer:
  lr: 2.0e-4
  betas: [0.9, 0.99]
  weight_decay: 0.0

scheduler:
  type: cosine
  warmup_steps: 800

loss:
  charbonnier_weight: 1.0
  edge_weight: 0.40
  perceptual_weight: 0.06
  antibanding_weight: 0.10
  antibanding_grad_thr: 0.02
  chroma_tv_weight: 0.04
  chroma_keep_weight: 0.20
  antihalo_weight: 0.03
  antihalo_edge_thr: 0.05
  antihalo_blur: 5
  tv_weight: 0.005
  use_gan: true
  gan_weight: 0.003
  r1_gamma: 10.0
  gan_warmup_steps: 1000

data:
  hr_dir: data/commons/images
  commons_dir: data/commons
  crop_size: 256
  use_tile_dataset: true
  tile_stride: 256
  scale_choices: [4]
  jpeg_q_range: [70, 95]
  noise_sigma_range: [0.0, 3.0]
  blur_kernel_size: 7
  blur_sigma_range: [0.2, 1.8]

train:
  mixed_precision: true
  ema: true
  ema_decay: 0.999
  grad_clip: 1.0
  compile: false

infer:
  tile_size: 384
  tile_overlap: 32
  temporal_smoothing: false
  smoothing_alpha: 0.7
  half_precision: true
  autotile: true
  min_tile: 128
  preserve_chroma: true
  post_sharpen:
    enabled: true
    amount: 0.45
    radius: 1
    threshold: 0.02
  tta: true
  self_finetune:
    enabled: true
    steps: 400
    in_patch: 128
    lr: 1.0e-4
    edge_weight: 0.4
    tv_weight: 0.0
    adapt_edges: true
    adapt_spectrum: false
    lpips_weight: 0.3
    edge_focus: true
    edge_focus_ratio: 0.7

paths:
  runs_dir: runs
  checkpoints_dir: runs/checkpoints
  logs_dir: runs/logs
  samples_dir: runs/samples